# Generated by Django 2.1.7 on 2019-03-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodreviews', '0002_review_rating2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating2',
        ),
    ]
