# Generated by Django 2.1.7 on 2019-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodreviews', '0017_auto_20190310_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='review',
            name='experience_text',
            field=models.TextField(max_length=10000),
        ),
    ]
