# Generated by Django 2.1.7 on 2019-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodreviews', '0025_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(null=True, upload_to='review-photos'),
        ),
    ]
