# Generated by Django 2.1.7 on 2019-03-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodreviews', '0026_auto_20190317_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
    ]
