# Generated by Django 2.1.7 on 2019-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodreviews', '0027_remove_review_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(null=True, upload_to='review-photos'),
        ),
    ]
